"""empty message

Revision ID: 015fbc0d7b18
Revises: a99513f1be90
Create Date: 2020-12-03 07:12:45.176850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015fbc0d7b18'
down_revision = 'a99513f1be90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Suffix', sa.Column('build', sa.String(), nullable=True))
    op.drop_constraint('Suffix_suffix_key', 'Suffix', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Suffix_suffix_key', 'Suffix', ['suffix'])
    op.drop_column('Suffix', 'build')
    # ### end Alembic commands ###
