"""empty message

Revision ID: 275d1feb45e7
Revises: f6bce6934ff6
Create Date: 2020-09-30 15:57:31.681191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275d1feb45e7'
down_revision = 'f6bce6934ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Suffix', sa.Column('Timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Suffix', 'Timestamp')
    # ### end Alembic commands ###
