"""empty message

Revision ID: 6cb9b6ecb07a
Revises: 275d1feb45e7
Create Date: 2020-09-30 16:11:56.060042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb9b6ecb07a'
down_revision = '275d1feb45e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ArrayMetric', sa.Column('suffix', sa.String(), nullable=True))
    op.drop_column('ArrayMetric', 'Suffix')
    op.add_column('Sfssum', sa.Column('suffix', sa.String(), nullable=True))
    op.drop_column('Sfssum', 'Suffix')
    op.add_column('Suffix', sa.Column('suffix', sa.String(), nullable=True))
    op.drop_column('Suffix', 'Suffix')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Suffix', sa.Column('Suffix', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Suffix', 'suffix')
    op.add_column('Sfssum', sa.Column('Suffix', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Sfssum', 'suffix')
    op.add_column('ArrayMetric', sa.Column('Suffix', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ArrayMetric', 'suffix')
    # ### end Alembic commands ###
