"""empty message

Revision ID: a4d5d7ee6789
Revises: 6cb9b6ecb07a
Create Date: 2020-09-30 16:57:20.413589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d5d7ee6789'
down_revision = '6cb9b6ecb07a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ArrayMetric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suffix', sa.String(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.Column('SpaCpu', sa.Float(), nullable=True),
    sa.Column('SpbCpu', sa.Float(), nullable=True),
    sa.Column('SpaTotalIOPS', sa.Float(), nullable=True),
    sa.Column('SpbTotalIOPS', sa.Float(), nullable=True),
    sa.Column('SpaAvgIOPS', sa.Float(), nullable=True),
    sa.Column('SpbAvgIOPS', sa.Float(), nullable=True),
    sa.Column('SpaRdKBPS', sa.Float(), nullable=True),
    sa.Column('SpbRdKBPS', sa.Float(), nullable=True),
    sa.Column('SpaWrtKBPS', sa.Float(), nullable=True),
    sa.Column('SpbWrtKBPS', sa.Float(), nullable=True),
    sa.Column('SpaAvgRdSize', sa.Float(), nullable=True),
    sa.Column('SpbAvgRdSize', sa.Float(), nullable=True),
    sa.Column('SpaAvgWrtSize', sa.Float(), nullable=True),
    sa.Column('SpbAvgWrtSize', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suffix')
    )
    op.create_table('Sfssum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suffix', sa.String(), nullable=False),
    sa.Column('BizMetric', sa.Integer(), nullable=True),
    sa.Column('ReqOpRate', sa.Float(), nullable=True),
    sa.Column('AchiOpRate', sa.Float(), nullable=True),
    sa.Column('AvgLat', sa.Float(), nullable=True),
    sa.Column('TotalKBps', sa.Float(), nullable=True),
    sa.Column('RdKBps', sa.Float(), nullable=True),
    sa.Column('WrtKBps', sa.Float(), nullable=True),
    sa.Column('RunSec', sa.Integer(), nullable=True),
    sa.Column('Cl', sa.Integer(), nullable=True),
    sa.Column('ClProc', sa.Integer(), nullable=True),
    sa.Column('AvgFileSizeKB', sa.Integer(), nullable=True),
    sa.Column('ClDataSetMiB', sa.Integer(), nullable=True),
    sa.Column('StartDataSetMiB', sa.Integer(), nullable=True),
    sa.Column('InitFileSetMiB', sa.Integer(), nullable=True),
    sa.Column('MaxFileSpaceMiB', sa.Integer(), nullable=True),
    sa.Column('WorkloadName', sa.String(), nullable=True),
    sa.Column('ValidRun', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suffix')
    )
    op.create_table('Suffix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suffix', sa.String(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Timestamp'),
    sa.UniqueConstraint('suffix')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Suffix')
    op.drop_table('Sfssum')
    op.drop_table('ArrayMetric')
    # ### end Alembic commands ###
