"""empty message

Revision ID: b8b0b96e4195
Revises: 015fbc0d7b18
Create Date: 2021-04-12 03:14:14.761305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b0b96e4195'
down_revision = '015fbc0d7b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Suffix', sa.Column('hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Suffix', 'hidden')
    # ### end Alembic commands ###
