"""empty message

Revision ID: f6bce6934ff6
Revises: 
Create Date: 2020-09-30 15:56:51.810394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6bce6934ff6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ArrayMetric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Suffix', sa.String(), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.Column('SpaCpu', sa.Float(), nullable=True),
    sa.Column('SpbCpu', sa.Float(), nullable=True),
    sa.Column('SpaTotalIOPS', sa.Float(), nullable=True),
    sa.Column('SpbTotalIOPS', sa.Float(), nullable=True),
    sa.Column('SpaAvgIOPS', sa.Float(), nullable=True),
    sa.Column('SpbAvgIOPS', sa.Float(), nullable=True),
    sa.Column('SpaRdKBPS', sa.Float(), nullable=True),
    sa.Column('SpbRdKBPS', sa.Float(), nullable=True),
    sa.Column('SpaWrtKBPS', sa.Float(), nullable=True),
    sa.Column('SpbWrtKBPS', sa.Float(), nullable=True),
    sa.Column('SpaAvgRdSize', sa.Float(), nullable=True),
    sa.Column('SpbAvgRdSize', sa.Float(), nullable=True),
    sa.Column('SpaAvgWrtSize', sa.Float(), nullable=True),
    sa.Column('SpbAvgWrtSize', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Sfssum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Suffix', sa.String(), nullable=True),
    sa.Column('BizMetric', sa.Integer(), nullable=True),
    sa.Column('ReqOpRate', sa.Float(), nullable=True),
    sa.Column('AchiOpRate', sa.Float(), nullable=True),
    sa.Column('AvgLat', sa.Float(), nullable=True),
    sa.Column('TotalKBps', sa.Float(), nullable=True),
    sa.Column('RdKBps', sa.Float(), nullable=True),
    sa.Column('WrtKBps', sa.Float(), nullable=True),
    sa.Column('RunSec', sa.Integer(), nullable=True),
    sa.Column('Cl', sa.Integer(), nullable=True),
    sa.Column('ClProc', sa.Integer(), nullable=True),
    sa.Column('AvgFileSizeKB', sa.Integer(), nullable=True),
    sa.Column('ClDataSetMiB', sa.Integer(), nullable=True),
    sa.Column('StartDataSetMiB', sa.Integer(), nullable=True),
    sa.Column('InitFileSetMiB', sa.Integer(), nullable=True),
    sa.Column('MaxFileSpaceMiB', sa.Integer(), nullable=True),
    sa.Column('WorkloadName', sa.String(), nullable=True),
    sa.Column('ValidRun', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Suffix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Suffix', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('Suffix')
    op.drop_table('Sfssum')
    op.drop_table('ArrayMetric')
    # ### end Alembic commands ###
